export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const ADD_TO_NEXT = 'ADD_TO_COUNTER';
export const CLEAR_TO_NEXT = 'CLEAR_TO_COUNTER';